version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: 'Borges'
      POSTGRES_USER: 'ADMIN'
      POSTGRES_PASSWORD : 'PASS'
    ports:
      - "5432:5432"
  flask_web:
    build: .
    command: python run.py
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
